// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gldigjxcjfdvlylsjztx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdsZGlnanhjamZkdmx5bHNqenR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk3MjAxNzYsImV4cCI6MjA3NTI5NjE3Nn0.D08JfK31ME0L_PV4HkPo1V-wOK4FXaM9ha4RHXdKkK8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});